/* =====================================================================
   ShippingDB — Web Edition (rebuilt from legacy WinForms schema + Requirement Doc V2)
   Target: Microsoft SQL Server 2016+
   NOTE: Your original ShippingDataBase.sql was not in the archive (only a .lnk
   shortcut). This script recreates and EXTENDS the schema used by the old
   Shippingrepository.cs, adding all V2 modules:
     - Users & session-based roles
     - Companies w/ Regular/Non-Regular status
     - Vessels w/ Confirm / Purchase / Catering / Generate / DeckEng emails
     - Vessel Types (seeded)
     - Countries / Ports / Port Sources (Ports Setup module)
     - Port Assignments (one port -> one user, no duplicates)
     - ScrapedData (Import Data staging, "Useless" handling, per-user distribution)
     - UselessVessels (global IMO ignore list)
     - ArrivalLog (date-wise history, Daily Report source)
   ===================================================================== */

IF DB_ID('ShippingDB') IS NULL
    CREATE DATABASE ShippingDB;
GO
USE ShippingDB;
GO

/* ───────────────────────── USERS ───────────────────────── */
IF OBJECT_ID('dbo.Users') IS NULL
CREATE TABLE dbo.Users (
    UserID        INT IDENTITY(1,1) PRIMARY KEY,
    Username      NVARCHAR(50)  NOT NULL UNIQUE,
    PasswordHash  NVARCHAR(200) NOT NULL,           -- PBKDF2 (iterations.salt.hash) generated by app
    FullName      NVARCHAR(100) NOT NULL,
    Role          NVARCHAR(20)  NOT NULL DEFAULT 'User',   -- 'Admin' | 'User'
    IsActive      BIT           NOT NULL DEFAULT 1,
    CreatedAt     DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
/* The application seeds a default admin (admin / Admin@123) on first run
   if this table is empty — see Program.cs. */

/* ───────────────────────── COMPANIES ───────────────────────── */
IF OBJECT_ID('dbo.Companies') IS NULL
CREATE TABLE dbo.Companies (
    CompanyID    INT IDENTITY(1,1) PRIMARY KEY,
    CompanyName  NVARCHAR(150) NOT NULL UNIQUE,
    Address      NVARCHAR(300) NULL,
    Country      NVARCHAR(80)  NULL,
    GeneralEmail NVARCHAR(200) NULL,
    Website      NVARCHAR(200) NULL,
    Telephone    NVARCHAR(60)  NULL,
    Status       NVARCHAR(20)  NOT NULL DEFAULT 'Non-Regular',  -- 'Regular' | 'Non-Regular'
    CreatedAt    DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

/* ───────────────────────── VESSEL TYPES ───────────────────────── */
IF OBJECT_ID('dbo.VesselTypes') IS NULL
CREATE TABLE dbo.VesselTypes (
    TypeID   INT IDENTITY(1,1) PRIMARY KEY,
    TypeName NVARCHAR(80) NOT NULL UNIQUE
);
GO
IF NOT EXISTS (SELECT 1 FROM dbo.VesselTypes)
INSERT INTO dbo.VesselTypes (TypeName) VALUES
('Asphalt Bitumen Tanker'),('Bulk Carrier'),('Bunkering Tanker'),('Cargo'),
('Cargo A'),('Cargo D'),('Cement Carrier'),('Chemical Oil Products Tanker'),
('Chemical Tanker'),('Container Ro Ro Cargo Ship'),('Container Ship'),
('Crude Oil Tanker'),('Cruise Ship'),('Deck Cargo Ship'),('Fruit Juice Tanker'),
('General Cargo'),('General Cargo Ship'),('Heavy Load Carrier'),('Limestone Carrier'),
('Livestock Carrier'),('LNG Tanker'),('LPG Tanker'),('Multi Purpose Carrier'),
('Oil Products Tanker'),('Oil/Chemical Tanker'),('Passenger Ro Ro Cargo Ship'),
('Reefer'),('Refrigerated Cargo Ship'),('Ro Ro Cargo Ship'),('Ro-Ro Cargo'),
('Self Discharging Bulk Carrier'),('Tanker'),('Tanker B'),('Tanker D'),
('Vehicles Carrier'),('Wood Chips Carrier');
GO

/* ───────────────────────── VESSELS ───────────────────────── */
IF OBJECT_ID('dbo.Vessels') IS NULL
CREATE TABLE dbo.Vessels (
    IMO_Number    VARCHAR(15)   NOT NULL PRIMARY KEY,   -- 7-digit IMO; saved/keyed by IMO per spec
    VesselName    NVARCHAR(150) NOT NULL,
    VesselTypeID  INT           NULL REFERENCES dbo.VesselTypes(TypeID),
    CallSign      NVARCHAR(30)  NULL,
    CompanyID     INT           NULL REFERENCES dbo.Companies(CompanyID),
    Port          NVARCHAR(100) NULL,
    ETA           NVARCHAR(60)  NULL,
    Country       NVARCHAR(80)  NULL,
    Address       NVARCHAR(300) NULL,
    PhoneNo       NVARCHAR(60)  NULL,
    Terms         NVARCHAR(30)  NULL,                   -- 'Credit' | 'Cash'
    -- Email fields (V2: Confirm / Purchase / Catering added & exported everywhere)
    ConfirmEmail  NVARCHAR(400) NULL,
    GenerateEmail NVARCHAR(400) NULL,
    DeckEngEmail  NVARCHAR(400) NULL,
    CateringEmail NVARCHAR(400) NULL,
    PurchaseEmail NVARCHAR(400) NULL,
    GeneralEmail  NVARCHAR(400) NULL,
    Status        NVARCHAR(30)  NOT NULL DEFAULT 'Active',
    CreatedAt     DATETIME2     NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt     DATETIME2     NULL
);
CREATE INDEX IX_Vessels_Name    ON dbo.Vessels(VesselName);
CREATE INDEX IX_Vessels_Company ON dbo.Vessels(CompanyID);
GO

/* ───────────────────────── COUNTRIES / PORTS / SOURCES (Ports Setup) ───── */
IF OBJECT_ID('dbo.Countries') IS NULL
CREATE TABLE dbo.Countries (
    CountryID   INT IDENTITY(1,1) PRIMARY KEY,
    CountryName NVARCHAR(80) NOT NULL UNIQUE,
    IsAsia      BIT NOT NULL DEFAULT 0          -- drives Asia / Non-Asia report split
);
GO
IF NOT EXISTS (SELECT 1 FROM dbo.Countries)
INSERT INTO dbo.Countries (CountryName, IsAsia) VALUES
('Pakistan',1),('UAE',1),('China',1),('India',1),('Singapore',1),
('Saudi Arabia',1),('Japan',1),('South Korea',1),
('USA',0),('United Kingdom',0),('Netherlands',0),('Germany',0),('Brazil',0);
GO

IF OBJECT_ID('dbo.Ports') IS NULL
CREATE TABLE dbo.Ports (
    PortID    INT IDENTITY(1,1) PRIMARY KEY,
    PortName  NVARCHAR(100) NOT NULL,
    CountryID INT NOT NULL REFERENCES dbo.Countries(CountryID),
    Notes     NVARCHAR(500) NULL,
    MaxPages  INT NOT NULL DEFAULT 50,          -- "first 50 pages" bulk rule
    CONSTRAINT UQ_Ports UNIQUE (PortName, CountryID)
);
GO

IF OBJECT_ID('dbo.PortSources') IS NULL
CREATE TABLE dbo.PortSources (
    SourceID         INT IDENTITY(1,1) PRIMARY KEY,
    PortID           INT NOT NULL REFERENCES dbo.Ports(PortID) ON DELETE CASCADE,
    SourceName       NVARCHAR(60)  NOT NULL,    -- 'MyShipTracking' | 'VesselFinder' | 'VesselTracker' | other
    Url              NVARCHAR(500) NOT NULL,
    PageParamPattern NVARCHAR(200) NULL,        -- e.g. '&page={n}' — pagination differs per site
    StartPage        INT NOT NULL DEFAULT 1,
    EndPage          INT NOT NULL DEFAULT 50,
    IsActive         BIT NOT NULL DEFAULT 1
);
GO

/* ───────────────────────── PORT ASSIGNMENTS (Admin → User) ─────────────── */
IF OBJECT_ID('dbo.PortAssignments') IS NULL
CREATE TABLE dbo.PortAssignments (
    AssignmentID INT IDENTITY(1,1) PRIMARY KEY,
    PortID       INT NOT NULL UNIQUE REFERENCES dbo.Ports(PortID) ON DELETE CASCADE, -- UNIQUE = no duplicate port assignment
    UserID       INT NOT NULL REFERENCES dbo.Users(UserID),
    AssignedAt   DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

/* ───────────────────────── USELESS VESSELS (global IMO ignore list) ────── */
IF OBJECT_ID('dbo.UselessVessels') IS NULL
CREATE TABLE dbo.UselessVessels (
    IMO_Number VARCHAR(15) NOT NULL PRIMARY KEY,
    Reason     NVARCHAR(200) NULL,
    MarkedBy   INT NULL REFERENCES dbo.Users(UserID),
    MarkedAt   DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

/* ───────────────────────── SCRAPED DATA (Import Data staging) ──────────── */
IF OBJECT_ID('dbo.ScrapedData') IS NULL
CREATE TABLE dbo.ScrapedData (
    ScrapeID      INT IDENTITY(1,1) PRIMARY KEY,
    VesselName    NVARCHAR(150) NOT NULL,
    IMO_Number    VARCHAR(15)   NULL,
    PortID        INT NULL REFERENCES dbo.Ports(PortID),
    PortName      NVARCHAR(100) NOT NULL,
    Country       NVARCHAR(80)  NOT NULL,
    ArrivalDate   NVARCHAR(60)  NULL,
    DepartureTime NVARCHAR(60)  NULL,
    Origin        NVARCHAR(120) NULL,
    VesselStatus  NVARCHAR(60)  NULL,
    DataSource    NVARCHAR(60)  NULL,
    Deadweight    NVARCHAR(30)  NULL,
    GrossTonnage  NVARCHAR(30)  NULL,
    VesselBuilt   NVARCHAR(20)  NULL,
    VesselType    NVARCHAR(80)  NULL,
    VesselSize    NVARCHAR(40)  NULL,
    IsMatched     BIT NOT NULL DEFAULT 0,
    IsUseless     BIT NOT NULL DEFAULT 0,        -- "Useless" button; excluded by all filters
    AssignedUserID INT NULL REFERENCES dbo.Users(UserID),  -- set by Auto Data distribution
    ImportDate    DATE NOT NULL DEFAULT CAST(GETDATE() AS DATE),
    CreatedAt     DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE INDEX IX_Scraped_UserDate ON dbo.ScrapedData(AssignedUserID, ImportDate);
CREATE INDEX IX_Scraped_IMO      ON dbo.ScrapedData(IMO_Number);
GO

/* ───────────────────────── ARRIVAL LOG (date-wise history) ─────────────── */
IF OBJECT_ID('dbo.ArrivalLog') IS NULL
CREATE TABLE dbo.ArrivalLog (
    LogID       INT IDENTITY(1,1) PRIMARY KEY,
    IMO_Number  VARCHAR(15)   NULL REFERENCES dbo.Vessels(IMO_Number),
    PortName    NVARCHAR(100) NOT NULL,
    Country     NVARCHAR(80)  NOT NULL,
    ArrivalDate DATE          NOT NULL,
    IsTagged    BIT           NOT NULL DEFAULT 0,  -- tagged rows excluded from export
    EnteredBy   INT NULL REFERENCES dbo.Users(UserID),
    CreatedAt   DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE INDEX IX_Arrival_DateCountry ON dbo.ArrivalLog(ArrivalDate, Country);
GO

/* ───────────────────────── EMAIL LOG (Auto Emails module) ──────────────── */
IF OBJECT_ID('dbo.EmailLog') IS NULL
CREATE TABLE dbo.EmailLog (
    EmailID     INT IDENTITY(1,1) PRIMARY KEY,
    Category    NVARCHAR(40)  NOT NULL,          -- Confirm | Purchase | Catering | Generate | DeckEng | General
    ToAddress   NVARCHAR(400) NOT NULL,
    Subject     NVARCHAR(300) NULL,
    Body        NVARCHAR(MAX) NULL,
    IMO_Number  VARCHAR(15)   NULL,
    VesselName  NVARCHAR(150) NULL,
    CompanyName NVARCHAR(150) NULL,
    Status      NVARCHAR(20)  NOT NULL DEFAULT 'Sent',  -- 'Sent' | 'Failed' | 'Logged'
    ErrorText   NVARCHAR(500) NULL,
    SentBy      INT NULL REFERENCES dbo.Users(UserID),
    SentVia     NVARCHAR(60)  NULL,              -- sending account used (Google / Hotmail / …)
    SentAt      DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE INDEX IX_EmailLog_SentAt ON dbo.EmailLog(SentAt DESC);
GO

/* ───────────────────────── EMAIL TEMPLATES (reusable presets) ──────────── */
IF OBJECT_ID('dbo.EmailTemplates') IS NULL
CREATE TABLE dbo.EmailTemplates (
    TemplateID  INT IDENTITY(1,1) PRIMARY KEY,
    Name        NVARCHAR(120) NOT NULL,
    Category    NVARCHAR(40)  NULL,              -- NULL = applies to any category
    Subject     NVARCHAR(300) NOT NULL,
    Body        NVARCHAR(MAX) NOT NULL,
    IsHtml      BIT NOT NULL DEFAULT 0,
    CreatedAt   DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt   DATETIME2 NULL
);
GO

/* ───────────────────────── VIEWS ───────────────────────── */
IF OBJECT_ID('dbo.vw_ArrivalDetail') IS NOT NULL DROP VIEW dbo.vw_ArrivalDetail;
GO
CREATE VIEW dbo.vw_ArrivalDetail AS
SELECT al.LogID, al.IMO_Number, al.PortName, al.Country, al.ArrivalDate, al.IsTagged, al.EnteredBy,
       v.VesselName, vt.TypeName AS VesselType, v.CallSign, v.Status,
       v.ConfirmEmail, v.PurchaseEmail, v.CateringEmail, v.GenerateEmail, v.DeckEngEmail, v.GeneralEmail,
       v.Terms,
       c.CompanyID, c.CompanyName, c.Address AS CompanyAddress, c.Country AS CompanyCountry,
       c.GeneralEmail AS CompanyEmail, c.Telephone, c.Website, c.Status AS CustomerStatus
FROM dbo.ArrivalLog al
LEFT JOIN dbo.Vessels    v  ON v.IMO_Number = al.IMO_Number
LEFT JOIN dbo.VesselTypes vt ON vt.TypeID    = v.VesselTypeID
LEFT JOIN dbo.Companies  c  ON c.CompanyID  = v.CompanyID;
GO

IF OBJECT_ID('dbo.vw_CompanyFleet') IS NOT NULL DROP VIEW dbo.vw_CompanyFleet;
GO
CREATE VIEW dbo.vw_CompanyFleet AS
SELECT c.CompanyID, c.CompanyName, c.Address, c.Country, c.GeneralEmail,
       c.Website, c.Telephone, c.Status,
       COUNT(v.IMO_Number) AS FleetCount
FROM dbo.Companies c
LEFT JOIN dbo.Vessels v ON v.CompanyID = c.CompanyID
GROUP BY c.CompanyID, c.CompanyName, c.Address, c.Country, c.GeneralEmail,
         c.Website, c.Telephone, c.Status;
GO

PRINT 'ShippingDB (Web) schema created/verified.';
GO
